### ISSUE TITLE
zh-CN Translation

### ISSUE THREAD

**Issue by Meteorite1014** [TheTimeSweeper/EnforcerMod#42]
I tried to translated them into my native language(simplified Chinese). 
[Enforcer.txt](https://github.com/TheTimeSweeper/EnforcerMod/files/13811587/Enforcer.txt)
[Nemforcer.txt](https://github.com/TheTimeSweeper/EnforcerMod/files/13811591/Nemforcer.txt)

**Comment by Moffein** [comment]
Merged as of https://github.com/TheTimeSweeper/EnforcerMod/pull/43
