### ISSUE TITLE
The game does not start with this mod

### ISSUE THREAD

**Issue by Zero000002** [TheTimeSweeper/EnforcerMod#45]
After the mod update, the game no longer opens, it loads up to 100%, the game doesn't crash or anything, but it just stays at 100% loaded and nothing happens
[LogOutput.log](https://github.com/user-attachments/files/15687585/LogOutput.log)

**Comment by Moffein** [comment]
Thanks for reporting this, seems like there was a formatting issue with the recently-added Portuguese translation.
Let me know if the latest update fixed it.

**Comment by Zero000002** [comment]
> Thanks for reporting this, seems like there was a formatting issue with the recently-added Portuguese translation. Let me know if the latest update fixed it.

Today's update appears to have fixed this 👍
